export enum Permission {
  CREATE_COMPANY = "create:company",
  UPDATE_COMPANY = "update:company",
  DELETE_COMPANY = "delete:company",
  VIEW_COMPANY = "view:company",
  CREATE_MEMBERS = "create:members",
  UPDATE_MEMBERS = "update:members",
  DELETE_MEMBERS = "delete:members",
  VIEW_MEMBERS = "view:members",
  CREATE_SERVICES = "create:services",
  UPDATE_SERVICES = "update:services",
  DELETE_SERVICES = "delete:services",
  VIEW_SERVICES = "view:services",
  CREATE_APPOINTMENTS = "create:appointments",
  UPDATE_APPOINTMENTS = "update:appointments",
  DELETE_APPOINTMENTS = "delete:appointments",
  VIEW_APPOINTMENTS = "view:appointments",
  CREATE_WORKHOURS = "create:workhours",
  UPDATE_WORKHOURS = "update:workhours",
  UPDATE_OWN_WORKHOURS = "update:own_workhours",
  DELETE_WORKHOURS = "delete:workhours",
  VIEW_WORKHOURS = "view:workhours",
  VIEW_CUSTOMERS = "view:customers",
}
